name: Deploy code

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up SSH
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Install yarn + pm2
        run: npm install --global yarn pm2

      - name: Deploy to server
        env:
          NEXT_PUBLIC_LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_LINE_CHANNEL_ACCESS_TOKEN }}
          NEXT_PUBLIC_LINE_CHANNEL_SECRET: ${{ secrets.NEXT_PUBLIC_LINE_CHANNEL_SECRET }}
          NEXT_PUBLIC_LINE_CLEANING_GROUP_ID: ${{ secrets.NEXT_PUBLIC_LINE_CLEANING_GROUP_ID }}
          NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL }}
          NEXT_PUBLIC_GOOGLE_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY }}
          NEXT_PUBLIC_CLEANING_GOOGLE_SHEET_ID: ${{ secrets.NEXT_PUBLIC_CLEANING_GOOGLE_SHEET_ID }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa root@167.179.72.25 << 'ENDSSH'
            cd /var/www/nanyaru/source
            
            # Tạo file .env trên server
            cat << EOF > .env
          NEXT_PUBLIC_LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_LINE_CHANNEL_ACCESS_TOKEN }}
          NEXT_PUBLIC_LINE_CHANNEL_SECRET=${{ secrets.NEXT_PUBLIC_LINE_CHANNEL_SECRET }}
          NEXT_PUBLIC_LINE_CLEANING_GROUP_ID=${{ secrets.NEXT_PUBLIC_LINE_CLEANING_GROUP_ID }}
          NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL }}
          NEXT_PUBLIC_GOOGLE_PRIVATE_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY }}
          NEXT_PUBLIC_CLEANING_GOOGLE_SHEET_ID=${{ secrets.NEXT_PUBLIC_CLEANING_GOOGLE_SHEET_ID }}
          IMGBB_API_KEY=${{ secrets.IMGBB_API_KEY }}
          EOF
            
            # Pull code mới
            git pull origin main
            
            # Build và restart
            yarn install --frozen-lockfile
            yarn build
            pm2 reload ecosystem.config.js
          ENDSSH